# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: dizinir_development
  username: postgres
  password: Iwbos6@1988
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: dizinir_test
  username: postgres
  password: Iwbos6@1988
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dizinir_production
  username: postgres
  password: Iwbos6@1988
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000